### ISSUE TITLE
Better toolgun display

### ISSUE THREAD

**Issue by arkadR** [arkadR/VisualParadise#14]
Add UI elements in the toolgun that will display what modes are enabled

**Comment by karol7531** [comment]
how about this for the gun:
https://free3d.com/3d-model/railgun-prototype-761517.html
and this for monitor:
https://www.turbosquid.com/3d-models/3d-sci-fi-panel-model-1214769

**Comment by arkadR** [comment]
I'll try those and let you know how it looks.
